app/student/forms.py
from wtforms.fields import StringField,SubmitField,SelectField,FileField
from wtforms.widgets import TextArea
from wtforms.validators import Required,Email,Length
from flask_wtf import FlaskForm
from tools.ectimezones import ectimezone_list

class PersonalInfoForm(FlaskForm):
    '''这是学生版个人信息的表单类'''
    image=FileField(label='Image')
    name=StringField(label='Your real name',validators=[Length(0,64)])
    location=StringField(label='Location',validators=[Length(0,64)],render_kw={'placeholder':'i.e. New York,US'})
    timezone=SelectField(label='Timezone',validators=[Required()],choices=ectimezone_list,description='Timezone is very important to booking lessons,please be careful.')
    username=StringField(label='Username',render_kw={'readonly':True},validators=[Required()])
    email=StringField(label='Email',validators=[Required(),Email()],render_kw={'readonly':True})
    member_since=StringField(label='Member since',validators=[Required()],render_kw={'readonly':True})
    submit=SubmitField(label='Submit')

class StudentRateForm(FlaskForm):
    '''这是学生给课程评分的表单类'''
    mark = SelectField(label="Rating",validators=[Required()],choices=[['0',0],['1',1],['2',2],['3',3],['4',4],['5',5]])
    s_comment = StringField(label="What do you think of this lesson?",validators=[Length(1,256)],widget=TextArea())
    submit = SubmitField(label='Submit')

app/student/__init__.py
from flask import Blueprint

student = Blueprint('student',__name__)

from . import views

app/student/views.py
from flask import current_app,url_for,render_template,redirect,flash,request,jsonify
from flask_login import current_user,login_required
from flask_sqlalchemy import Pagination
from . import student
from .forms import PersonalInfoForm,StudentRateForm
from ..models import User,Lesson,Order,MakeUpTime,Permission
import os
from ..import db
from datetime import datetime,timedelta
from pytz import country_timezones,timezone
import calendar
from calendar import monthcalendar,monthrange,Calendar
from tools.ectimezones import get_localtime
from tools.decorators import permission_required

#个人信息
@student.route('/personal_info',methods=['GET','POST'])
@login_required
def personal_info():
    '''这是学生的个人信息视图'''
    form = PersonalInfoForm()
    if form.validate_on_submit():
        user=current_user._get_current_object()
        user.name = form.name.data
        user.location = form.location.data
        user.timezone = form.timezone.data
        if 'image' in request.files:
            file = request.files['image']
            if file:
                cleaned_filename=User.validate_image(file.filename)
                UPLOAD_FOLDER = current_app.config['UPLOAD_FOLDER']
                file.save(os.path.join(UPLOAD_FOLDER,cleaned_filename))
                user.image = cleaned_filename
        db.session.add(user)
        flash('Successfully modified your personal information')
        return redirect(url_for('student.personal_info'))

    form.image.data = current_user.image
    form.name.data = current_user.name
    form.location.data = current_user.location
    form.timezone.data = current_user.timezone
    form.username.data = current_user.username
    form.email.data = current_user.email
    form.member_since.data = current_user.member_since.strftime('%Y-%m-%d')
    return render_template('student/personal_info.html',form=form)

#取消已选课程
@student.route('/cancel',methods=['GET','POST'])
@login_required
@permission_required(Permission.BOOK_LESSON)
def cancel():
    '''取消相应的课程'''
    lesson_id = request.form.get("id",0,type=int)
    if lesson_id:
        lesson=Lesson.query.get_or_404(lesson_id)
        #还要看看时间是不是超过10分钟
        if (lesson.time-datetime.utcnow()).seconds >= 600:
            lesson.is_delete=True
            db.session.add(lesson)
            # 还要把课时还到课时包里面
            # 我们要从最新的课时包开始，找到第一个不满(也就是left_amount<lesson_amount的课时包)，把还给学生的课加到这个包里
            all_packages = lesson.student.orders.filter(Order.pay_status=='paid').order_by(Order.id.desc()).all()
            for package in all_packages:
                if package.left_amount <package.lesson_amount:
                    package.left_amount += 1
                    break
            db.session.add(package)
            return jsonify({'status':'ok'})
        return jsonify({"status":"fail"})
    return jsonify({'status':'fail'})

#给课程评分
@student.route('/rate/<lesson_id>',methods=['GET','POST'])
@login_required
@permission_required(Permission.BOOK_LESSON)
def rate(lesson_id):
    lesson = Lesson.query.get_or_404(lesson_id)
    if current_user.id != lesson.student_id:
        flash("You can not rate a lesson that does not belong to you.")
        return redirect(url_for("main.personal_center"))
    form = StudentRateForm()
    if form.validate_on_submit():
        lesson.mark = int(form.mark.data)
        lesson.s_comment = form.s_comment.data
        db.session.add(lesson)
        flash("Rated successfully!")
        return redirect(url_for("main.personal_center"))
    flash("You'd better double check before you submit your rating ,because you're not allowed to modify it.")
    return render_template('student/student_rate.html',form=form)
    
#我的课时包
@student.route('/my_packages')
@login_required
@permission_required(Permission.BOOK_LESSON)
def my_packages():
    '''
    这是学生的所有课时包页面
    '''
    #这是未付款的课时包
    new_orders=current_user.orders.filter(Order.pay_status=='waiting').order_by(Order.id.desc()).all()
    for order in new_orders:
        order.teacher=User.query.get(order.teacher_id)
    #下面是已付款的课时包
    old_orders = current_user.orders.filter(Order.pay_status=='paid').order_by(Order.id.desc()).all()
    #学生的时区
    tz=current_user.timezone
    if len(tz)==2:
        tz = country_timezones[tz][0] 
    else:
        tz = country_timezones[tz[:2]][int(tz[3:])]
    tz = timezone(tz)
    utc = timezone('UTC')
    for order in old_orders:
        order.teacher=User.query.get(order.teacher_id)
        start = datetime(order.pay_time.year,order.pay_time.month,order.pay_time.day,order.pay_time.hour,tzinfo=utc)
        local_start = start.astimezone(tz)
        order.local_start = local_start
        end = datetime(order.end_time.year,order.end_time.month,order.end_time.day,order.end_time.hour,tzinfo=utc)
        local_end = end.astimezone(tz)
        order.local_end = local_end
    return render_template('student/my_packages.html',new_orders=new_orders,old_orders=old_orders)

#学生选课
@student.route('/book_lesson',methods=['GET','POST'])
@login_required
@permission_required(Permission.BOOK_LESSON)
def book_lesson():
    '''这是学生订课的视图'''
    # 找到该学生的老师
    teacher = User.query.filter_by(id=current_user.student_profile.first().teacher_id).first()
    # 学生可能还没有分配老师，我们只操作分配了老师的情况
    if teacher:
        #取出老师的工作时间字符串并转化为列表 
        worktime=teacher.work_time.first().work_time
        worktime_list = worktime.split(';')

        #把以星期为单位的教师工作时间转化为UTC年月日小时的时间
        #第一步：构造出UTC的此时此刻
        cal = Calendar(6)  # 让每个星期都从星期天开始
        utc = timezone('UTC')
        utcnow = datetime.utcnow()
        utcnow = datetime(utcnow.year,utcnow.month,utcnow.day,utcnow.hour,tzinfo=utc)
        # 第二步：计算出可以选课的起始时间，也就是此时此刻的24小时后，以及截至时间，也就是现在开始的29天后
        available_start = utcnow+timedelta(1)
        available_end = utcnow + timedelta(29)
        # 第三步：找到起始日期和结束日期所在的星期，拼接出可以选课的28天的列表，
        # 大列表里的小列表代表一个个以周日开始的星期
        start_flag = False
        all_available_dates = []
        for week in cal.monthdatescalendar(available_start.year,available_start.month):
            # 在没找到起始日期所在的星期的时候，要检查这个星期是否就是我们寻找的
            if not start_flag and available_start.date() in week:
                start_flag = True
            # 从找到了起始日期所在的星期开始，我们要把它所在的以及它后面的星期加到列表里
            if start_flag:
                all_available_dates.append(week)
                
        # 遍历结束日期所在的月，如果当前星期不在列表里，就添加(因为前后两个月可能有重复的星期)
        # 遇到结束日期所在的星期，后面的就不用看了
        for week in cal.monthdatescalendar(available_end.year,available_end.month):
            if available_end not in week:
                all_available_dates.append(week)
            if available_end.date() in week:
                break
    

        # 第四步：根据老师的工作时间，构造出以datetime对象为元素的列表
        # 创建一个空列表，存放老师的以小时为单位的工作时间
        new_worktime_list = []
        for week in all_available_dates:
            # w是类似于0-1这样的字符串，它表示星期天的UTC时间1点钟
            for w in worktime_list:
                date = week[int(w[0])]
                time = datetime(date.year,date.month,date.day,int(w[2:]),tzinfo=utc)
                if time<available_start or time>available_end:
                    continue
                new_worktime_list.append(time)
        # 第五步：把教师的特殊休息时间去掉
        special_rest_set = set()
        temp = teacher.special_rest.filter_by(expire=False).all()
        for data in temp:
            rest_time = datetime(data.rest_time.year,data.rest_time.month,data.rest_time.day,data.rest_time.hour,tzinfo=utc)
            if rest_time>=available_start:
                special_rest_set.add(rest_time)
            else:
                data.expire = True
                db.session.add(data)
        for i in new_worktime_list[:]:
            if i in special_rest_set:
                new_worktime_list.remove(i)
        # 第六步：把教师的补班时间加进去(这一步要放在前面，因为可能补班的时间也被选上课了)
        makeup_time_list=[]
        # 先把当前显示没有过期的补班时间都查出来
        temp = teacher.make_up_time.filter_by(expire=False).all()
        for data in temp:
            makeup_time = datetime(data.make_up_time.year,data.make_up_time.month,data.make_up_time.day,data.make_up_time.hour,tzinfo=utc)
            if makeup_time>=available_start:
                makeup_time_list.append(makeup_time)
            # 如果补班时间在可选开始时间之前，说明事实上已经过期了
            # 把expire改为True
            else:
                data.expire = True
                db.session.add(data)
            
        new_worktime_list+=makeup_time_list
        # 第七步：生成一个已预约的课程时间列表，并把这些时间从老师的工作时间里去掉
        # 为了节约资源，我们在查询的时候就筛选一下时间
        lessons = Lesson.query.filter(Lesson.teacher_id == teacher.id,Lesson.is_delete==False,Lesson.time>=datetime.utcnow()+timedelta(1)).all()
        # 先用set存放时间，因为查询比较快
        lessons_set = set()
        for lesson in lessons:
            time = lesson.time
            time = datetime(time.year,time.month,time.day,time.hour,tzinfo=utc)
            lessons_set.add(time)
        for i in new_worktime_list[:]:
            if i in lessons_set:
                new_worktime_list.remove(i)
        lessons_list = list(lessons_set)
        
        #计算出游客的时区
        visitor_country=current_user.timezone
        if len(visitor_country)>2:
            visitor_tz = country_timezones[visitor_country[:2]][int(visitor_country[-1])]
        else:
            visitor_tz = country_timezones[visitor_country][0]
        tz_obj = timezone(visitor_tz)

        # 根据时区，生成游客视角的可以选课的28天的日历
        visitor_start = get_localtime(available_start,current_user)
        visitor_end = get_localtime(available_end,current_user)
        
        visitor_dates = []
        start_flag = False
        for week in cal.monthdatescalendar(visitor_start.year,visitor_start.month):
            # 因为遍历一个星期也会浪费时间，所以我们这里设两个条件
            # 如果flag已经是True了，就不需要再看结束日期在不在这个星期里了
            if not start_flag and visitor_start.date() in week:

app/templates/student/book_lesson.html
{%extends 'student/homepage.html'%}
{%block head%}
{{super()}}
<style>

.table{
    width:729.6px;
}
h3{
    margin-bottom:20px;
}
.available,.available-s{
    background-color:#5cb85c;
}
    
.available:hover{
    cursor: pointer;
}
    
.booked,.booked-s{
    background-color:#d9534f;
}
    
.rest,.rest-s{
    background-color: white;
}
    
.selected,.selected-s{
    background-color: #777777;
}
    
.legend{
    display:inline-block;
    width:40px;
    height:20px;
    border:1px solid #efefef;
}
.legend-info{
    font-size: 16px;
}
    </style>
{%endblock head%}

{%block title%}
Book A Lesson
{%endblock title%}

{%block main%}
{%if teacher%}
<div class='col-sm-6 col-md-8'>
    <h4>Here is your teacher {{teacher.name}}'s schedule.</h4>
    <h3 class='text-center'>{{month_name}} , {{year}}</h3>
    <nav aria-label="...">
        <ul class="pager">
          <li {%if current_page.has_prev%}class="previous"{%else%}class='previous disabled'{%endif%}><a {%if current_page.has_prev%}href="{{url_for('student.book_lesson',page=current_page.prev_num)}}"{%endif%}><span aria-hidden="true">&larr;</span>Previous Week</a></li>
          <li {%if current_page.has_next %}class="next"{%else%}class='next disabled'{%endif%}><a {%if current_page.has_next %}href="{{url_for('student.book_lesson',page=current_page.next_num)}}"{%endif%}>Next Week <span aria-hidden="true">&rarr;</span></a></li>
        </ul>
    </nav>
    <h4>
        <span class='legend available-s'></span>
        <span class='legend-info'>available</span>
        <span class='legend booked-s'></span>
        <span class='legend-info'>booked</span>
        <span class='legend rest-s'></span>
        <span class='legend-info'>unavailable</span>
        <span class='legend selected-s'></span>
        <span class='legend-info'>selected</span>
    </h4>
    <table class='table'>
        <tr>
            <th class='col-md-2 col-sm-1 col-xs-2 text-right'></th>
            <th class='col-md-1 col-sm-1 col-xs-1 text-right'>Sunday</th>
            <th class='col-md-1 col-sm-1 col-xs-1 text-right'>Monday</th>
            <th class='col-md-1 col-sm-1 col-xs-1 text-right'>Tuesday</th>
            <th class='col-md-1 col-sm-1 col-xs-1 text-right'>Wednesday</th>
            <th class='col-md-1 col-sm-1 col-xs-1 text-center'>Thursday</th>
            <th class='col-md-1 col-sm-1 col-xs-1 text-center'>Friday</th>
            <th class='col-md-1 col-sm-1 col-xs-1 text-center'>Saturday</th>
        </tr>
        <tr>
            
            <th class='col-md-2 col-sm-2 col-xs-2 text-right'></th>
            {% for date in only_dates%}
            <th class='col-md-1 col-sm-1 col-xs-1 text-right'>{{date}}</th>
            {%endfor%}
        </tr>
    </table>
    <table class='table table-bordered'>
        {% for hour in range(24)%}
        <tr>
            
            <td class='col-md-2 col-sm-2 col-xs-2 text-center'>{{hour}}:00-{{hour}}:50</td>
            {% for date in this_week%}
            <td {%if '%s-%s'|format(date,hour) in lessons_list %}class='col-md-1 col-sm-1 col-xs-1 booked'{% elif '%s-%s'|format(date,hour) in new_worktime_list %} class='col-md-1 col-sm-1 col-xs-1 available'{%else%}class='col-md-1 col-sm-1 col-xs-1'{%endif%} id="{{'%s-%s'|format(date,hour)}}"></td>
            {% endfor %}
        </tr>
        {%endfor%}
    </table> 
    <!-- end of the schedule -->
    <div class='form-group text-right'>
        <button class='btn btn-default' type='button' id='submit'>Submit</button>
    </div>
</div>
<!-- end of the whole right part -->

{%else%}
<div class='col-sm-8 col-md-8' id='main'>
    <div class='panel panel-default'>
        <div class='panel-body'>
            <h3>You haven't got a teacher yet. Please wait.</h3>
        </div>
    </div><!-- end of panel -->
</div><!-- end of #main -->
{%endif%}
{%endblock main%}

{%block scripts%}
{{super()}}

<script>
$(function(){
    //获取csrftoken
    var csrftoken = '{{csrf_token()}}'
    //定义一个变量，上课时间
    var time = ''
    //下面是获取上课时间的点击事件
    $('.available').click(function(){
        if($(this).attr('class')=="col-md-1 col-sm-1 col-xs-1 available"){
            time=$(this).attr('id')
            //当一个时间点变成了选中状态的时候，其他被选中的时间点要变成可选状态，保证一次只能选择一个时间点
            $('.selected').attr('class','col-md-1 col-sm-1 col-xs-1 available');
            $(this).attr('class','col-md-1 col-sm-1 col-xs-1 selected');
        }else{
            //点击已经选中的时间点，会取消对它的选择
            $(this).attr('class','col-md-1 col-sm-1 col-xs-1 available');
            time=''
        }
    })
    
    $('#submit').click(function(){
        //如果上课时间为空，弹出警告
        if(time==''){
            alert("Time is necessary.")
        }else{ //否则就要提交选课的ajax请求了
            $.ajax({
                type:'POST',
                url:"{{url_for('student.book_lesson')}}",
                data:{
                      time:time,
                },
                headers:{'X-CSRFToken':csrftoken},
                success:function(callback){
                    alert(callback.msg);
                    window.location.reload();

                }
            })//ajax的结尾
        }//else的结尾
    })//click的结尾

  
})
</script>
{%endblock scripts%}

app/templates/student/homepage.html
{% extends 'base.html'%}
{%block head%}
{{super()}}
<style>
#main{
    margin-bottom: 300px;
}

.cancel:hover{
    color:blue;
    cursor: pointer;
}
</style>
{%endblock head%}
{%block mytitle%}Personal Center{%endblock mytitle%}

{%block page_content%}
<div class='page-header'>
    <h1>Personal Center</h1>
</div>
<div class='col-sm-3 col-md-3' >
    <ul class='nav nav-pills nav-stacked'>
        <li role="presentation" {%if request.path[:11] == '/personal_c'  or request.path[:10]=='/student/r'%}class='active'{%endif%}><a href="{{url_for('main.personal_center')}}">My Lessons</a></li>
        <li role="presentation" {%if request.path[:10] == '/student/b'%} class ='active'{%endif%}><a href="{{url_for('student.book_lesson')}}">Book a lesson</a></li>
        <li role='presentation' {%if request.path[:10] =='/student/m'%} class='active' {%endif%}><a href="{{url_for('student.my_packages')}}">My Packages</a></li>
        <li role="presentation" {%if request.path[:10] == '/student/p'%}class='active'{%endif%}><a href="{{url_for('student.personal_info')}}">Personal Information</a></li>    
    </ul>
</div>
{%block main%}
<div class='col-sm-8 col-md-8' id='main'>
    <div class='panel panel-default'>
        <table class='table'>
            <tr>
                <th>Teacher</th>
                <th>Time</th>
                <th>Status</th>
                <th>Teacher's comment</th>
                <th>Rate</th>
            </tr>
            {%for lesson in lessons%}
            <tr>
                <td><a href='#'>{{lesson.teacher.name}}</a></td>
                <td>{{"%s-%s-%s %s:00"|format(lesson.localtime.year,lesson.localtime.month,lesson.localtime.day,lesson.localtime.hour)}}</td>
                <td>{% if lesson.status == 'Not started' and moment().valueOf()>moment(lesson.time).valueOf() %} Waiting for comment{%else%}{{lesson.status}}{%endif%}</td>
                <td>{%if lesson.status == 'Not started' and lesson.cancel %}<span class='cancel' lid={{lesson.id}}>[Cancel]</span>{%endif%}{%if lesson.t_comment %}{{lesson.t_comment}}{%endif%}</td>
                <td>{% if moment().valueOf()>moment(lesson.time).valueOf()%} {% if not lesson.s_comment %}<a href="{{url_for('student.rate',lesson_id=lesson.id)}}">Do it now</a>{%else%}Done{%endif%}{%endif%}</td>
            </tr>
            {%endfor%}
            

        </table>
    </div>
</div>
{%endblock main%}
{%endblock page_content%}

{%block scripts%}
{{super()}}
<script>
$(function(){
    //获取csrftoken
    var csrftoken = '{{csrf_token()}}'
    var cancel=$(".cancel");
    cancel.bind("click",function(){
        var id=$(this).attr("lid");
        var answer=confirm('Are you sure to cancel this lesson?');
        if(answer==true){
            $.ajax({
            url:"{{url_for('student.cancel')}}",
            type:"POST",
            data:{id:id},
            headers:{'X-CSRFToken':csrftoken},
            success:function(callback){
                if(callback.status=='ok'){
                    alert("That lesson has been canceled successfully.")
                    window.location.reload();
                }else{
                    alert("Operation failed.");
                }
                }
            })
        }
        
    })
})
</script>
{{moment.include_moment()}}
{%endblock scripts%}

app/templates/student/my_packages.html
{%extends 'student/homepage.html'%}
{%block head%}
{{super()}}
{%endblock head%}

{%block title%}My Packages{%endblock title%}

{%block main%}
<div class='col-xs-12 col-sm-9' id='main'>
    <div class='panel panel-default'>
        <div class='panel-heading'>
            <h4>Unpaid packages</h4>
        </div>
        
        <table class='table'>
            {% if new_orders %}
            <tr>
                <th>Order id</th>
                <th>Lesson type</th>
                <th>Lessons</th>
                <th>Time limit</th>
                <th>Price</th>
                <th>Teacher</th>
                <th></th>
            </tr>
            {%for order in new_orders%}
            <tr>
                <td>{{order.id}}</td>
                <td>{{order.lesson_type}} Course</td>
                <td>{{order.lesson_amount}}</td>
                <td>{%if order.time_limit == 12%}1 year{%elif order.time_limit==24%}2 years{%else%}{{order.time_limit}} months{%endif%}</td>
                <td>${{order.price}}</td>
                <td>{{order.teacher.name}}</td>
                <td><button class='btn btn-primary' order-id={{order.id}}>Pay now</button></td>
            </tr>
            {%endfor%}
            {%else%}
            <tr>
                <td>You don't have unpaid packages. Click <a href="{{url_for('pay.course_info')}}">here</a> to see the course details.</td>
            </tr>
            {%endif%}
        </table>
    </div> <!-- end of unpaid packages -->

    <div class='panel panel-default'>
        <div class='panel-heading'>
            <h4>Paid packages</h4>
        </div>
        <table class='table'>
            <tr>
                <th>Order id</th>
                <th>Lesson type</th>
                <th>Left lessons</th>
                <th>Start</th>
                <th>End</th>
                <th>Teacher</th>
            </tr>
            {%for order in old_orders%}
            <tr>
                <td>{{order.id}}</td>
                <td>{{order.lesson_type}} Course</td>
                <td>{{order.left_amount}}/{{order.lesson_amount}}</td>
                <td>{{"%s-%s-%s %s:00"|format(order.local_start.year,order.local_start.month,order.local_start.day,order.local_start.hour)}}</td>
                <td>{{"%s-%s-%s %s:00"|format(order.local_end.year,order.local_end.month,order.local_end.day,order.local_end.hour)}}</td>
                <td>{{order.teacher.name}}</td>
            </tr>
            {%endfor%}
        </table>
    </div>
</div>
{%endblock main%}

{%block scripts%}
{{super()}}
<script>
$(function(){
    $('button').click(function(){
        var order_id = $(this).attr('order-id');
        console.log(order_id);
        $.ajax({
            type:'GET',
            url:"{{url_for('pay.pay_order')}}",
            data:{order_id:order_id},
            success:function(callback){
                if(callback.status=='ok'){
                    location.href=callback.msg;
                }
                else if(callback.status=='fail'){
                    alert(callback.msg);
                }
            }
        })
    })
})
</script>
{%endblock scripts%}

app/templates/student/personal_info.html
{%extends 'student/homepage.html'%}
{%import 'bootstrap/wtf.html' as wtf%}
{%block head %}
{{super()}}
<style>
#user-image{
    width:200px;
    height:200px;
}
</style>
{%endblock head%}

{%block mytitle %}Personal Information{%endblock mytitle%}

{%block main%}
<div class='col-sm-8 col-md-8' id='main'>
    <div class='panel panel-default'>
        <div class='panel-body'>
            <div>
            <img {%if current_user.image%}src="{{url_for('static',filename='media/'+current_user.image)}}"{%else%}src="{{url_for('static',filename='img/noimage.jpg')}}"{%endif%} class='img-thumbnail' id='user-image'>
            </div>
            {{wtf.quick_form(form)}}
        </div>
    </div>
</div>
{%endblock main%}

app/templates/student/student_rate.html
{%extends 'student/homepage.html'%}
{%import 'bootstrap/wtf.html' as wtf%}
{%block head%}
{{super()}}
{%endblock head%}

{%block mytitle %}Student Rating{%endblock mytitle%}

{%block main%}
<div class='col-sm-8 col-md-8' id='main'>
    <div class='panel panel-default'>
        <div class='panel-body'>
            {{wtf.quick_form(form)}}
        </div>
    </div>
</div>
{%endblock main%}