app/teacher/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import StringField,SelectField,SubmitField,FileField
from wtforms.validators import Required,Email,Length
from wtforms.widgets import TextArea
from tools.ectimezones import ectimezone_list

class PersonalInfoForm(FlaskForm):
    '''这是教师个人信息的表单'''
    image=FileField(label='Image')
    name=StringField(label='Your real name',validators=[Required(),Length(1,64)])
    location=StringField(label='Location',validators=[Length(0,64)],render_kw={'placeholder':'i.e. New York,US'})
    timezone=SelectField(label='Timezone',validators=[Required()],choices=ectimezone_list,description='Timezone is very important to booking lessons,please be careful.')
    username=StringField(label='Username',render_kw={'readonly':True},validators=[Required()])
    email=StringField(label='Email',validators=[Required(),Email()],render_kw={'readonly':True})
    member_since=StringField(label='Member since',validators=[Required()],render_kw={'readonly':True})
    submit=SubmitField(label='Submit')

class EditProfileForm(FlaskForm):
    '''这是主管学生信息的表单'''
    nickname = StringField(label='称呼',validators=[Length(1,64)],render_kw={'placeholder':'学生喜欢的称呼，如Michael,陈先生等。如果发音比较特殊，也请标注。'})
    gender = StringField(label='性别',validators=[Length(1,32)])
    age = StringField(label='年龄',validators=[Length(1,32)])
    job = StringField(label='工作情况',validators=[Length(1,128)])
    family = StringField(label='家庭情况',validators=[Length(1,128)])
    personality = StringField(label='性格特点',validators=[Length(1,128)])
    hobby = StringField(label='兴趣爱好',validators=[Length(1,128)])
    taboo = StringField(label='禁忌话题',validators=[Length(1,128)],render_kw={'placeholder':'如学生比较敏感的宗教问题，去世的亲人或离异的父母、伴侣等。'})
    reason = StringField(label='学习原因',validators=[Length(1,128)])
    goal = StringField(label='学习目标',validators=[Length(1,128)],render_kw={'placeholder':'请尽量覆盖听说读写等多个方面'})
    level = StringField(label='当前水平',validators=[Length(1,128)],render_kw={'placeholder':'请尽量覆盖听说读写等多个方面'})
    ability = StringField(label='学习能力',validators=[Length(1,128)])
    notes = StringField(label='是否需要笔记或录音',validators=[Length(1,128)])
    homework = StringField(label='是否需要作业',validators=[Length(1,128)])
    teacher_phone = StringField(label='主管老师电话',validators=[Length(1,128)])
    submit = SubmitField(label='修改并提交')

class RecordLessonForm(FlaskForm):
    '''这是记录课程详情的表单类'''
    talk = StringField(label='寒暄',validators=[Length(1,256)],widget=TextArea())
    this_lesson = StringField(label='这节课学了什么',validators=[Length(1,256)],widget=TextArea())
    next_lesson = StringField(label='下节课安排',validators=[Length(1,256)],widget=TextArea())
    homework = StringField(label='作业',validators=[Length(1,256)],widget=TextArea())
    textbook = StringField(label='教材',validators=[Length(1,256)],render_kw={'placeholder':'请写清楚教材名称、版本以及册数，如《新实用汉语课本》第2版第一册'},widget=TextArea())
    other = StringField(label='其他注意事项',validators=[Length(1,256)],widget=TextArea())
    status = SelectField(label='课时完成状态',validators=[Required()],choices=[['Complete','正常完成'],['Stu Absent','学生缺勤'],['Tea Absent','教师缺勤'],['Tea Late','教师迟到']])
    t_comment = StringField(label='对学生表现的评价',validators=[Length(1,256)],widget=TextArea())
    submit = SubmitField(label='提交')

app/teacher/__init__.py
from flask import Blueprint

teacher = Blueprint('teacher',__name__)

from . import views

app/teacher/views.py
from flask import render_template,request,current_app,redirect,url_for,flash
from flask_login import current_user,login_required
from . import teacher
from .forms import PersonalInfoForm,EditProfileForm,RecordLessonForm
from pytz import timezone,country_timezones
from datetime import datetime
from ..models import User,Lesson,StudentProfile,LessonRecord,Order,Permission
from .. import db
import os
from tools.ectimezones import get_localtime
from tools.decorators import permission_required

#教师个人信息
@teacher.route('/personal_info',methods=['GET','POST'])
@login_required
def personal_info():
    '''这是个人信息的视图'''
    form = PersonalInfoForm()
    if form.validate_on_submit():
        user = current_user._get_current_object()
        if 'image' in request.files:
            file = request.files['image']
            if file:
                UPLOAD_FOLDER = current_app.config['UPLOAD_FOLDER']
                cleaned_filename = User.validate_image(file.filename)
                file.save(os.path.join(UPLOAD_FOLDER,cleaned_filename))
                user.image = cleaned_filename
                user.name = form.name.data
                user.location = form.location.data
                user.timezone = form.timezone.data
                flash('Successfully modified your personal imformation')
                return redirect(url_for('teacher.personal_info'))                
            else:
                if user.image:
                    user.name = form.name.data
                    user.location = form.location.data
                    user.timezone = form.timezone.data
                    flash('Successfully modified your personal information')
                    return redirect(url_for('teacher.personal_info'))
                else:
                    flash('教师头像不能为空')
                    return redirect(url_for('teacher.personal_info'))
        else:
            if user.image:
                user.name = form.name.data
                user.location = form.location.data
                user.timezone = form.timezone.data
                db.session.add(user)
                flash('Successfully modified your personal information')
                return redirect(url_for('teacher.personal_info'))
            else:
                flash('教师头像不能为空')
                return redirect(url_for('teacher.personal_info'))
        
    form.email.data = current_user.email
    form.username.data = current_user.username
    form.name.data = current_user.name
    form.image.data = current_user.image
    form.location.data = current_user.location
    form.timezone.data = current_user.timezone
    #用户的注册时间在数据库里是一个utc的datetime对象，但是并没有tzinfo
    #所以这里要先构造成tzinfo为utc的datetime对象，再转化为tzinfo为学生时区的datetime对象
    utc = timezone('UTC')
    if len(current_user.timezone) > 2:
        user_tz = country_timezones[current_user.timezone[:2]][int(current_user.timezone[3:])]
    else:
        user_tz = country_timezones[current_user.timezone][0]
    user_tz = timezone(user_tz)
    time = current_user.member_since
    utc_member_since = datetime(time.year,time.month,time.day,time.hour,time.minute,time.second,tzinfo=utc)
    local_member_since = utc_member_since.astimezone(user_tz)
    form.member_since.data = local_member_since.strftime('%Y-%m-%d')
    return render_template('teacher/personal_info.html',form=form)

#我的所有学生
@teacher.route('/my_students')
@login_required
@permission_required(Permission.MANAGE_STUDENT_PROFILE)
def my_students():
    '''这是我的所有学生的视图'''
    username = request.args.get('username','',type=str)
    student = []
    lessons = []
    primary_teacher = []
    tab = request.args.get('tab','',type=str)
    #如果有用户名，就要查看某个学生的信息，否则就查看该教师的所有学生
    if username:
        student = User.query.filter_by(username=username).first()
        tz = current_user.timezone
        if len(tz) == 2:
            tz_str = country_timezones[tz][0]
        else:
            tz_str = country_timezones[tz[:2]][int(tz[3:])]
        tz = timezone(tz_str)
        utc = timezone('UTC')
        #查看该学生的所有课程
        if tab == 'lessons':
            lessons = student.lessons.filter_by(is_delete=False).order_by(Lesson.time.desc()).all()
            
            #给每节课添加教师信息，以及根据教师时区转化出的教师当地的上课时间
            for lesson in lessons:
                teacher = User.query.get(lesson.teacher_id)
                lesson.teacher = teacher
                utctime = datetime(lesson.time.year,lesson.time.month,lesson.time.day,lesson.time.hour,tzinfo=utc)
                localtime = utctime.astimezone(tz)
                lesson.localtime = localtime
        #查看该学生的个人信息
        elif tab == 'profile':
            member_since = student.member_since
            utcsince = datetime(member_since.year,member_since.month,member_since.day,member_since.hour,tzinfo=utc)
            localsince = utcsince.astimezone(tz)
            student.localsince = localsince
            student.timezone_str = tz_str
            teacher_id = student.student_profile.first().teacher_id
            primary_teacher = User.query.get(teacher_id)
        return render_template('teacher/my_students.html',username=username,student=student,tab=tab,lessons=lessons,primary_teacher=primary_teacher)
    #如果没有用户名，那就查询我的所有学生
    student_profiles = StudentProfile.query.filter_by(teacher_id=current_user.id).all()
    students=[]
    for profile in student_profiles:
        # 通过学生简历找到学生用户
        student = profile.student
        # 先把全部已支付的课时包的query对象查出来，一会儿要多次使用
        all_packages = student.orders.filter(Order.pay_status=='paid')
        # 查询该学生的课时类型
        active_packages = all_packages.filter(Order.left_amount>0).order_by(Order.id.asc()).all()
        # 如果有活跃课时包（里面还有剩余课时的课时包），那学生的课时类型就是最老的课时包的类型
        if active_packages:
            lesson_type = active_packages[0].lesson_type
        # 如果没有活跃课时包，那学生的课时类型就是最新的已完成的课时包的类型
        else:
            lesson_type = all_packages.order_by(Order.id.desc()).first().lesson_type
        student.lesson_type = lesson_type

        # 查询该学生的全部课时数和全部剩余课时数
        all_packages = all_packages.all()
        total_lessons = 0
        total_left = 0
        for package in all_packages:
            total_lessons += package.lesson_amount
            total_left += package.left_amount
        student.total_left = total_left
        student.total_finished = total_lessons-total_left
        if student.last_seen:
            local_last_seen = get_localtime(student.last_seen,current_user)
        else:
            local_last_seen = None
        student.local_last_seen = local_last_seen
        students.append(student)
    return render_template('teacher/my_students.html',students=students)

#修改主管学生信息
@teacher.route('/edit_profile/<username>',methods=['GET','POST'])
@login_required
@permission_required(Permission.MANAGE_STUDENT_PROFILE)
def edit_profile(username):
    '''修改主管学生信息'''
    student = User.query.filter_by(username=username,role_id=2).first()
    if student:
        utc = timezone('UTC')
        tz = current_user.timezone
        if len(tz) == 2:
            tz = country_timezones[tz][0]
        else:
            tz = country_timezones[tz[:2]][int(tz[3:])]
        tz = timezone(tz)
        member_since = student.member_since
        utcsince = datetime(member_since.year,member_since.month,member_since.day,member_since.hour,tzinfo=utc)
        localsince = utcsince.astimezone(tz)
        student.localsince = localsince
    student_profile = student.student_profile.first()
    form = EditProfileForm()
    if form.validate_on_submit():
        student_profile.nickname = form.nickname.data
        student_profile.gender = form.gender.data
        student_profile.age = form.age.data
        student_profile.job = form.job.data
        student_profile.family = form.family.data
        student_profile.personality = form.personality.data
        student_profile.hobby = form.hobby.data
        student_profile.taboo = form.taboo.data
        student_profile.reason = form.reason.data
        student_profile.goal = form.goal.data
        student_profile.level = form.level.data
        student_profile.ability = form.ability.data
        student_profile.notes = form.notes.data
        student_profile.homework = form.homework.data
        student_profile.teacher_phone = form.teacher_phone.data
        db.session.add(student_profile)
        flash("主管学生信息修改成功！")
        return redirect(url_for('teacher.my_students',username=username,tab='profile'))

    if student_profile:
        form.nickname.data = student_profile.nickname
        form.gender.data = student_profile.gender
        form.age.data = student_profile.age
        form.job.data = student_profile.job
        form.family.data = student_profile.family
        form.personality.data = student_profile.personality
        form.hobby.data = student_profile.hobby
        form.taboo.data = student_profile.taboo
        form.reason.data = student_profile.reason
        form.goal.data = student_profile.goal
        form.level.data = student_profile.level
        form.ability.data = student_profile.ability
        form.notes.data = student_profile.notes
        form.homework.data = student_profile.homework
        form.teacher_phone.data = student_profile.teacher_phone

    return render_template('teacher/edit_profile.html',student=student,form=form)

#填写课程详情
@teacher.route('/record_lesson/<int:id>',methods=['GET','POST'])
@login_required
@permission_required(Permission.RECORD_LESSON_DETAIL)
def record_lesson(id):
    '''这是填写课程详情的视图'''
    lesson = Lesson.query.get_or_404(id)
    lesson.localtime = get_localtime(lesson.time,current_user)
    
    form = RecordLessonForm()
    # 可能是修改，也可能是新建
    record = lesson.lesson_record.first() or LessonRecord()
    if not record.lesson_id:
        record.lesson_id = lesson.id

app/templates/teacher/check_detail.html
{% extends 'teacher/homepage.html'%}
{%block head%}
{{super()}}
<style>
footer{
    margin-top:300px;
}
</style>
{%endblock head%}

{%block title%}Check Detail{%endblock title%}
{%block main%}
<div class='col-sm-8 col-md-8'>
    <div class='panel panel-default'>
        <div class='panel-heading text-center'>
            <strong>课程详情</strong>
        </div>
        <div class='panel-body'>
            <table class='table'>
                <tr>
                    <th>学生</th>
                    <th>老师</th>
                    <th>上课时间</th>
                    <th>完成状态</th>
                </tr>
                <tr>
                    <td>{{lesson.student.username}}</td>
                    <td>{{lesson.teacher.name}}</td>
                    <td>{{"%s-%s-%s %s:00"|format(lesson.localtime.year,lesson.localtime.month,lesson.localtime.day,lesson.localtime.hour)}}</td>
                    <td>{{lesson.c_status}}</td>
                </tr>

            </table>
            <table class='table'>
                <tr>
                    <th>寒暄</th>
                </tr>
                <tr>
                    <td>{{record.talk}}</td>
                </tr>
                <tr>
                    <th>这节课学了什么</th>
                </tr>
                <tr>
                    <td>{{record.this_lesson}}</td>
                </tr>
                <tr>
                    <th>下节课安排</th>
                </tr>
                <tr>
                    <td>{{record.next_lesson}}</td>
                </tr>
                <tr>
                    <th>作业</th>
                </tr>
                <tr>
                    <td>{{record.homework}}</td>
                </tr>
                <tr>
                    <th>教材</th>
                </tr>
                <tr>
                    <td>{{record.textbook}}</td>
                </tr>
                <tr>
                    <th>其他注意事项</th>
                </tr>
                <tr>
                    <td>{{record.other}}</td>
                </tr>
            </table>

        </div>

    </div>

</div>
{%endblock main%}

app/templates/teacher/edit_profile.html
{%extends 'teacher/homepage.html'%}
{%import 'bootstrap/wtf.html' as wtf%}

{%block head%}
{{super()}}
<style>

</style>
{%endblock head%}

{%block mytitle%}Edit Profile{%endblock mytitle%}

{%block main%}
<div class='col-sm-8 col-md-8' id='main'>
    <div class='panel panel-default'>
        <div class='panel-heading text-center'>
            <strong>基本信息</strong>
        </div>
        <div class='panel-body'>
            <div class='col-sm-6 col-md-5 col-lg-4'>
                <img {%if student.image %}src="{{url_for('static',filename='media/'+student.image)}}" {%else%}src="{{url_for('static',filename='img/noimage.jpg')}}" {%endif%}class='img-thumbnail' id='user-image'>
            </div><!-- end of image -->
            <div class='col-sm-5 col-md-6 col-lg-7'>
                <table class='table'>
                    <tr>
                        <td><strong>用户名</strong></td>
                        <td>{{student.username}}</td>
                    </tr>
                    <tr>
                        <td><strong>姓名</strong></td>
                        <td>{{student.name}}</td>
                    </tr>
                    <tr>
                        <td><strong>邮箱</strong></td>
                        <td>{{student.email}}</td>
                    </tr>
                    <tr>
                        <td><strong>地址</strong></td>
                        <td>{{student.location}}</td>
                    </tr>
                    <tr>
                        <td><strong>课程类型</strong></td>
                        <td>Regular</td>
                    </tr>
                    <tr>
                        <td><strong>注册时间</strong></td>
                        <td>{{"%s-%s-%s"|format(student.localsince.year,student.localsince.month,student.localsince.day)}}</td>
                    </tr>
                    <tr>
                        <td><strong>最后一次上课</strong></td>
                        <td>2 weeks ago</td>
                    </tr>
                </table>
            </div><!-- end of other basic information -->
        </div><!-- end of panel body -->
    </div> <!-- end of the first panel -->

    <div class ='panel panel-default'>
        <div class='panel-heading text-center'>
            <strong>主管老师补充的信息</strong>
        </div>
        <div class='panel panel-body'>
            {{wtf.quick_form(form)}}

        </div>
    </div>
</div>

{%endblock main%}

app/templates/teacher/homepage.html
{% extends 'base.html'%}
{%block head%}
{{super()}}
<style>
#main{
    margin-bottom: 300px;
}
</style>
{%endblock head%}
{%block mytitle%}Personal Center{%endblock mytitle%}

{%block page_content%}
<div class='page-header'>
    <h1>Personal Center</h1>
</div>
<div class='col-sm-3 col-md-3' >
    <ul class='nav nav-pills nav-stacked'>
        <li role="presentation" {%if request.path[:11] == '/personal_c' or request.path[:10] == '/teacher/r' %}class='active'{%endif%}><a href="{{url_for('main.personal_center')}}">My Lessons</a></li>
        <li role="presentation" {%if request.path[:10] == '/teacher/m' or request.path[:10] == '/teacher/e'%}class='active'{%endif%}><a href="{{url_for('teacher.my_students')}}">My Students</a></li>
        <li role="presentation" {%if request.path[:10] == '/teacher/p'%}class='active'{%endif%}><a href="{{url_for('teacher.personal_info')}}">Personal Information</a></li>    
    </ul>
</div>
{%block main%}
<div class='col-sm-8 col-md-8' id='main'>
    <div class='panel panel-default'>
        <table class='table'>
            <tr>
                <th>Student</th>
                <th>Time</th>
                <th>Status</th>
                <th>Lesson Type</th>
                <th>Student's Comment</th>
            </tr>
            {%for lesson in lesson_list%}
            <tr>
                <td><a href="{{url_for('teacher.my_students',tab='lessons',username=lesson.student.username)}}">{{lesson.student.username}}</a></td>
                <td>{{"%s-%s-%s %s:00"|format(lesson.localtime.year,lesson.localtime.month,lesson.localtime.day,lesson.localtime.hour)}}</td>
                <td>{% if moment().valueOf()>moment(lesson.time).valueOf()%}<a href="{{url_for('teacher.record_lesson',id=lesson.id)}}">Record</a>{%else%}Not started{%endif%}</td>
                <td>{{lesson.lesson_type}}</td>
                <td></td>
            </tr>
            {%endfor%}

        </table>
    </div>
</div>
{%endblock main%}
{%endblock page_content%}

{%block scripts%}
{{super()}}
{{moment.include_moment()}}
{%endblock scripts%}

app/templates/teacher/my_students.html
{% extends 'teacher/homepage.html'%}

{%block head%}
{{super()}}
<style>
footer{
    margin-top: 200px;
}

ul.nav-tabs{
    margin-bottom: 20px;
}

#user-image{
    width:200px;
    height:200px;

}
</style>
{%endblock head%}

{%block mytitle%}My Students{%endblock mytitle%}

{%block main%}


<div class='col-sm-8 col-md-8' id='main'>
{%if username%}

<ul class="nav nav-tabs">
        <li role="presentation" {%if tab == 'lessons'%}class="active"{%endif%}><a href="{{url_for('teacher.my_students',tab='lessons',username=username)}}">Lessons</a></li>
        <li role="presentation"{%if tab == 'profile'%}class='active'{%endif%}><a href="{{url_for('teacher.my_students',tab='profile',username=username)}}">Profile</a></li>
    </ul>

    {%if tab =='lessons'%}
    <div class = 'panel panel-default'>
        <table class='table'>
            <tr>
                <th>Student</th>
                <th>Teacher</th>
                <th>Time</th>
                <th>Status</th>
                <th>Details</th>
            </tr>
            {%for lesson in lessons%}
            <tr>
                <td>{{student.username}}</td>
                <td>{{lesson.teacher.name}}</td>
                <td>{{"%s-%s-%s %s:00"|format(lesson.localtime.year,lesson.localtime.month,lesson.localtime.day,lesson.localtime.hour)}}</td>
                <td>{%if lesson.status == 'Not started'%}{%if moment().valueOf()>moment(lesson.time).valueOf()%}<a href="{{url_for('teacher.record_lesson',id=lesson.id)}}">Record</a>{%else%}Not started{%endif%}{%else%}{{lesson.status}}{%endif%}</td>
                <td>{%if lesson.status == 'Complete' or lesson.status == 'Tea Late'%}<a href="{{url_for('teacher.check_detail',id=lesson.id)}}">[Check]</a>{%endif%} {%if current_user.id == lesson.teacher.id%}<a href="{{url_for("teacher.record_lesson",id=lesson.id)}}">[Modify]</a>{%endif%}</td>
            </tr>
            {%endfor%}
        </table>
    </div>
    {%elif tab == 'profile'%}
    <div class='panel panel-default'>
        <div class='panel-heading text-center'>
            <strong>基本信息</strong> 
        </div>
        <div class='panel-body'>
            <div class='col-sm-6 col-md-5 col-lg-4'>
            <img {%if student.image %}src="{{url_for('static',filename='media/'+student.image)}}" {%else%}src="{{url_for('static',filename='img/noimage.jpg')}}" {%endif%}class='img-thumbnail' id='user-image'>
            </div><!-- end of image -->
            <div class='col-sm-5 col-md-6 col-lg-7'>
                <table class='table'>
                    <tr>
                        <td><strong>用户名</strong></td>
                        <td>{{student.username}}</td>
                    </tr>
                    <tr>
                        <td><strong>姓名</strong></td>
                        <td>{{student.name}}</td>
                    </tr>
                    <tr>
                        <td><strong>邮箱</strong></td>
                        <td>{{student.email}}</td>
                    </tr>
                    <tr>
                        <td><strong>地址</strong></td>
                        <td>{{student.location}}</td>
                    </tr>
                    <tr>
                        <td><strong>时区</strong></td>
                        <td>{{student.timezone_str}}</td>
                    </tr>
                    <tr>
                        <td><strong>课程类型</strong></td>
                        <td>Regular</td>
                    </tr>
                    <tr>
                        <td><strong>注册时间</strong></td>
                        <td>{{"%s-%s-%s"|format(student.localsince.year,student.localsince.month,student.localsince.day)}}</td>
                    </tr>
                    <tr>
                        <td><strong>最后一次上课</strong></td>
                        <td>2 weeks ago</td>
                    </tr>
                </table>
            </div>
        </div><!-- end of panel body -->
    </div><!-- end of panel -->

    <div class='panel panel-default'>
        <div class='panel-heading text-center'>
            <strong>主管老师的补充信息</strong>
        </div>
        <div class='panel-body'>
            <table class='table'>
                <tr>
                    <td><strong>称呼</strong></td>
                    <td>{{student.student_profile.first().nickname}}</td>
                    <td><strong>性别</strong></td>
                    <td>{{student.student_profile.first().gender}}</td>
                </tr>
                <tr>
                    <td><strong>年龄</strong></td>
                    <td>{{student.student_profile.first().age}}</td>
                    <td><strong>工作情况</strong></td>
                    <td>{{student.student_profile.first().job}}</td>
                </tr>
                <tr>
                    <td><strong>家庭情况</strong></td>
                    <td>{{student.student_profile.first().family}}</td>
                    <td><strong>性格特点</strong></td>
                    <td>{{student.student_profile.first().personality}}</td>
                </tr>
                <tr>
                    <td><strong>兴趣爱好</strong></td>
                    <td>{{student.student_profile.first().hobby}}</td>
                    <td><strong>禁忌话题</strong></td>
                    <td>{{student.student_profile.first().taboo}}</td>
                </tr>
                <tr>
                    <td><strong>学习原因</strong></td>
                    <td>{{student.student_profile.first().reason}}</td>
                    <td><strong>学习目标</strong></td>
                    <td>{{student.student_profile.first().goal}}</td>
                </tr>
                <tr>
                    <td><strong>当前水平</strong></td>
                    <td>{{student.student_profile.first().level}}</td>
                    <td><strong>学习能力</strong></td>
                    <td>{{student.student_profile.first().ability}}</td>
                </tr>
                <tr>
                    <td><strong>是否需要笔记或录音</strong></td>
                    <td>{{student.student_profile.first().notes}}</td>
                    <td><strong>是否需要作业</strong></td>
                    <td>{{student.student_profile.first().homework}}</td>
                </tr>
                <tr>
                    <td><strong>主管老师</strong></td>
                    <td>{{primary_teacher.name}}</td>
                    <td><strong>主管老师电话</strong></td>
                    <td>{{student.student_profile.first().teacher_phone}}</td>
                </tr>

            </table>
        </div>

    </div>
    {%if current_user.id == primary_teacher.id%}
    <div>
        <a class='btn btn-default col-lg-offset-9 col-md-offset-9 col-sm-offset-9 col-xs-offset-9' href="{{url_for('teacher.edit_profile',username=student.username)}}">修改主管学生信息</a>
    </div>
    {%endif%}
    {%endif%}
{%else%}
    <div class='panel panel-default'>
        <table class='table'>
            <tr>
                <th>Student</th>
                <th>Last seen</th>
                <th>Lesson Type</th>
                <th>Class Hours</th>
                <th>Remaining Hours</th>
            </tr>
            {%for student in students%}
            <tr>
                <td><a href="{{url_for('teacher.my_students',tab='lessons',username=student.username)}}">{{student.username}}</a></td>
                <td>{% if student.local_last_seen%}{{"%s-%s-%s %s:00"|format(student.local_last_seen.year,student.local_last_seen.month,student.local_last_seen.day,student.local_last_seen.hour)}}{%else%}--:--{%endif%}</td>
                <td>{{student.lesson_type}}</td>
                <td>{{student.total_finished}}</td>
                <td>{{student.total_left}}</td>
            </tr>
            {%endfor%}
        </table>
    </div>
    {%endif%}
</div><!-- end of main -->


{%endblock main%}

{%block scripts%}
{{super()}}
{{moment.include_moment()}}
{%endblock scripts%}

app/templates/teacher/personal_info.html
{%extends 'teacher/homepage.html'%}
{% import 'bootstrap/wtf.html' as wtf%}
{%block head%}
{{super()}}
<style>
#user-image{
    height:200px;
    width:200px;
}
</style>

{%endblock head%}

{%block mytitle%}Personal Infomation{%endblock mytitle%}
{%block main%}
<div class='col-sm-8 col-md-8' id='main'>
    <div class='panel panel-default'>
        <div class='panel-body'>
            <div>
            <img {%if current_user.image%}src="{{url_for('static',filename='media/'+current_user.image)}}"{%else%}src="{{url_for('static',filename='img/noimage.jpg')}}"{%endif%} class='img-thumbnail' id='user-image'>
            </div>
            {{wtf.quick_form(form)}}
        </div>
    </div>
</div>
{%endblock main%}

app/templates/teacher/record_lesson.html
{%extends 'teacher/homepage.html' %}
{% import 'bootstrap/wtf.html' as wtf%}

{%block head%}
{{super()}}
<style>
footer{
    margin-top:300px;
}
</style>
{%endblock head%}

{%block title%}Record Lesson{%endblock title%}

{%block main%}
<div class='col-sm-8 col-md-8'>
    <div class='panel panel-default'>
        <div class='panel-heading text-center'>
            <strong>课程详情</strong>
        </div> 
        <div class='panel-body'>
            <table class='table'>
                <tr>
                    <th>学生</th>
                    <th>上课时间</th>
                    <th>课程类型</th>
                </tr>
                <tr>
                    <td>{{lesson.student.username}}</td>
                    <td>{{"%s-%s-%s %s:00"|format(lesson.localtime.year,lesson.localtime.month,lesson.localtime.day,lesson.localtime.hour)}}</td>
                    <td>{{lesson.lesson_type}}</td>
                </tr>
            </table>
            {{wtf.quick_form(form)}}
        </div>
    </div>
</div>

{%endblock main%}