app/administrator/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import StringField,SubmitField,SelectField,BooleanField,DateTimeField,PasswordField
from wtforms.validators import Required,Length,Email,EqualTo
from tools.ectimezones import ectimezone_list
from tools.teacher_list1 import teacher_list1
from tools.visitor_student_list1 import visitor_student_list1



class PersonalInfoForm(FlaskForm):
    '''个人信息'''
    name=StringField(label='Your real name',validators=[Required(),Length(1,64)])
    location=StringField(label='Location',validators=[Length(0,64)],render_kw={'placeholder':'i.e. New York,US'})
    timezone=SelectField(label='Timezone',validators=[Required()],choices=ectimezone_list,description='Timezone is very important to booking lessons,please be careful.')
    username=StringField(label='Username',render_kw={'readonly':True},validators=[Required()])
    email=StringField(label='Email',validators=[Required(),Email()],render_kw={'readonly':True})
    member_since=StringField(label='Member since',validators=[Required()],render_kw={'readonly':True})
    submit=SubmitField(label='Submit')


class AssignTeacherForm(FlaskForm):
    '''这是新生分配老师的表单类'''
    username = StringField(label='学生',render_kw={'readonly':True})
    old_teachers = StringField(label='未见面的试听课老师',render_kw={'readonly':True})
    primary_teacher = SelectField(label='主管老师',choices=teacher_list1,validators=[Required()])
    submit = SubmitField(label='提交')

class ChangeTeacherForm(FlaskForm):
    '''这是给在校生更换老师的表单类'''
    username = StringField(label='学生',render_kw={'readonly':True},validators=[Required()])
    old_teachers = StringField(label='过去的老师',render_kw={'readonly':True})
    current_teacher = StringField(label='现任主管老师',render_kw={'readonly':True})
    new_teacher = SelectField(label='新主管老师',choices=teacher_list1,validators=[Required()])
    submit = SubmitField(label='提交')

class PreBookLessonForm(FlaskForm):
    '''这是帮助学生选课的预处理表单类'''
    student = SelectField(label='学生',choices=visitor_student_list1,validators=[Required()])
    teacher = SelectField(label='老师',choices=teacher_list1,validators=[Required()])
    submit = SubmitField(label='提交')

class ModifyPersonalInfoForm(FlaskForm):
    '''这是修改游客、学生和老师的信息的表单类'''
    username = StringField(label='用户名',render_kw={'readonly':True})
    name = StringField(label='姓名',validators=[Length(0,64)])
    role_id = SelectField(label='角色',choices=[['1','游客'],['2','学生'],['3','教师'],['4','协管员']])
    timezone = SelectField(label='时区',choices=ectimezone_list,validators=[Required()])
    is_delete = BooleanField(label='已删除',false_values=('False',))
    submit = SubmitField(label='提交')

class PreModifyScheduleForm(FlaskForm):
    '''这是修改教师工作时间的预处理视图'''
    teacher = SelectField(label='教师',choices=teacher_list1)
    time_type = SelectField(label='时间类型',choices=[['1','临时休息'],['2','补班'],['3','修改常规工作时间'],['4','取消休息'],['5','取消补班']])
    submit = SubmitField(label='提交')

class RestTimeForm(FlaskForm):
    '''这是临时休息时间表单'''
    teacher = StringField(label='教师',render_kw={'readonly':True})
    rest_type = SelectField(label='休息类型',choices=[['off','请假'],['meet','会议'],['lieu','调休']])
    start = DateTimeField(label='起始时间',validators=[Required()],description='格式:2008-8-18 8:00:00,请以你自己所在时区为准')
    end = DateTimeField(label='结束时间',validators=[Required()],description='格式:2008-8-18 9:00:00,请你以自己所在时区为准')
    submit = SubmitField(label='提交')

class MakeupTimeForm(FlaskForm):
    '''这是补班时间表单'''
    teacher = StringField(label='教师',render_kw={'readonly':True})
    start = DateTimeField(label='起始时间',validators=[Required()],description='格式:2008-8-18 8:00:00,请以你自己所在时区为准')
    end = DateTimeField(label='结束时间',validators=[Required()],description='格式:2008-8-18 8:00:00,请以你自己所在时区为准')
    submit = SubmitField(label='提交')

class ModifyPasswordForm(FlaskForm):
    '''这是修改老师们的密码的表单'''
    teacher = SelectField(label='教师',choices=teacher_list1)
    password=PasswordField(label='密码',validators=[Required(),Length(1,128),EqualTo('password2',message='The two passwords should be the same.')])
    password2=PasswordField(label='确认密码',validators=[Required(),Length(1,128)])
    submit = SubmitField(label='提交')

app/administrator/__init__.py
from flask import Blueprint

administrator = Blueprint('administrator',__name__)

from . import views

app/administrator/views.py
from . import administrator

from flask import url_for,render_template,redirect,request,flash,jsonify
from flask_login import login_required,current_user
from .forms import AssignTeacherForm,PersonalInfoForm,ChangeTeacherForm,PreBookLessonForm,ModifyPersonalInfoForm,PreModifyScheduleForm,RestTimeForm,MakeupTimeForm,ModifyPasswordForm
from tools.ectimezones import get_localtime,get_utctime
from app import db
from ..models import User,Order,Lesson,SpecialRest,MakeUpTime,Permission,WorkTime
from datetime import datetime,timedelta
from pytz import country_timezones,timezone
from calendar import Calendar
import calendar
from flask_sqlalchemy import Pagination
from tools.decorators import admin_required,permission_required

# 管理员的个人信息
@administrator.route('/personal_info',methods=['GET','POST'])
@login_required
def personal_info():
    '''管理员的个人信息'''
    form = PersonalInfoForm()
    if form.validate_on_submit():
        user = current_user._get_current_object()
        user.name = form.name.data
        user.location = form.location.data
        user.timezone = form.timezone.data
        db.session.add(user)
        flash('成功修改个人信息')
        return redirect(url_for('administrator.personal_info'))
    form.email.data = current_user.email
    form.username.data = current_user.username
    form.name.data = current_user.name
    form.location.data = current_user.location
    form.timezone.data = current_user.timezone
    local_member_since = get_localtime(current_user.member_since,current_user)
    form.member_since.data = local_member_since.strftime('%Y-%m-%d')
    return render_template('administrator/personal_info.html',form=form)

# 给还没有老师的新生分配老师
@administrator.route('/assign_teacher/<username>',methods=['GET','POST'])
@login_required
@permission_required(Permission.MANAGE_RELATIONSHIP)
def assign_teacher(username):
    '''这是给新生分配老师的视图

    :参数 username:学生的用户名
    '''
    student = User.query.filter_by(username=username).first()
    if student:
        form = AssignTeacherForm()
        if form.validate_on_submit():
            teacher_username = form.primary_teacher.data
            teacher = User.query.filter_by(username=teacher_username).first()
            teacher_id = teacher.id
            student_profile = student.student_profile.first()
            student_profile.teacher_id = teacher_id
            db.session.add(student_profile)
            return redirect(url_for('main.personal_center'))
        form.username.data = username
        # 学生的第一个订单里保存了过去的老师
        old_teacher_ids = student.orders.filter_by(pay_status='paid').order_by(Order.pay_time.asc()).first().past_teachers
        if old_teacher_ids:
            old_teacher_ids_list = old_teacher_ids.split(';')
            past_teachers_names = User.query.get(old_teacher_ids_list[0]).name
            for oid in old_teacher_ids_list[1:]:
                past_teachers_names=past_teachers_names+';'+User.query.get(oid).name
            form.old_teachers.data = past_teachers_names
        return render_template('administrator/assign_teacher.html',form=form) 

# 显示全校学生名单，为查看学生的信息做准备
@administrator.route('/check_students')
@login_required
@permission_required(Permission.BOOK_LESSON_FOR_OTHERS)
def check_students():
    students = User.query.filter_by(role_id=2,is_delete=False).order_by(User.username.asc()).all()
    all_students = []
    count = 0
    temp = []
    for student in students:
        temp.append(student)
        count += 1
        if count == 4:
            all_students.append(temp)
            temp = []
            count = 0
    if temp:
        all_students.append(temp)

    return render_template('administrator/check_students.html',all_students=all_students)

# 查看学生的信息
@administrator.route('/show_student_profile/<username>')
@login_required
@permission_required(Permission.BOOK_LESSON_FOR_OTHERS)
def show_student_profile(username):
    '''查看学生的个人信息

    :参数 username:学生的用户名'''
    student = User.query.filter_by(username=username).first()
    if student:
        tab = request.args.get('tab','',type=str)
        if tab == 'lessons':
            lessons = student.lessons.filter_by(is_delete=False).order_by(Lesson.time.desc()).all()
            for lesson in lessons:
                lesson.teacher = User.query.get(lesson.teacher_id)
                lesson.localtime = get_localtime(lesson.time,current_user)
                # 开课十分钟前，课程是可以取消的
                if lesson.time>datetime.utcnow()+timedelta(0,600):
                    lesson.cancel = True
                else:
                    lesson.cancel = False
            return render_template('administrator/student_profile.html',student=student,tab=tab,lessons=lessons,username=username)
        elif tab == 'profile':
            teacher_id = student.student_profile.first().teacher_id
            if teacher_id:
                student.teacher = User.query.get(teacher_id)
            else:
                student.teacher = None
            student.localsince = get_localtime(student.member_since,current_user)
            student_country=student.timezone
            if len(student_country)>2:
                student.timezone_str = country_timezones[student_country[:2]][int(student_country[-1])]
            else:
                student.timezone_str = country_timezones[student_country][0]
            
            return render_template('administrator/student_profile.html',student=student,tab=tab,username=username)

# 查看一节课的详情
@administrator.route('/check_detail/<lesson_id>')
@login_required
@permission_required(Permission.BOOK_LESSON_FOR_OTHERS)
def check_detail(lesson_id):
    lesson = Lesson.query.get_or_404(lesson_id)
    status_dict = {'Complete':'正常完成','Tea Absent':'教师缺勤','Stu Absent':'学生缺勤','Tea Late':'教师迟到'}
    #添加中文描述的课时完成状态
    lesson.c_status = status_dict[lesson.status]
    #添加本节课的教师对象
    teacher = User.query.get(lesson.teacher_id)
    lesson.teacher = teacher
    #添加用户以用户时区为标准的上课时间对象
    lesson.localtime = get_localtime(lesson.time,current_user)
    record = lesson.lesson_record.first()
    return render_template('administrator/check_detail.html',lesson=lesson,record=record)

# 显示全校学生名单，为更换老师做准备
@administrator.route('/pre_change_teacher')
@login_required
@permission_required(Permission.MANAGE_RELATIONSHIP)
def pre_change_teacher():
    students = User.query.filter_by(role_id=2,is_delete=False).order_by(User.username.asc()).all()
    all_students = []
    count = 0
    temp = []
    for student in students:
        temp.append(student)
        count += 1
        if count == 4:
            all_students.append(temp)
            temp = []
            count = 0
    if temp:
        all_students.append(temp)
    
    return render_template('administrator/pre_change_teacher.html',all_students=all_students)  


# 更换老师
@administrator.route('/change_teacher/<username>',methods=['GET','POST'])
@login_required
@permission_required(Permission.MANAGE_RELATIONSHIP)
def change_teacher(username):
    '''给在校生更换老师

    :参数 username:学生的用户名'''
    student = User.query.filter_by(username=username,is_delete=False).first()
    if student:
        form = ChangeTeacherForm()
        # 获取学生的第一个订单，因为那里面保存了一些过去的老师
        first_order = student.orders.filter_by(pay_status='paid').order_by(Order.pay_time.asc()).first()
        # 获取学生的简历
        student_profile = student.student_profile.first()
        if form.validate_on_submit():
            new_teacher_username = form.new_teacher.data
            new_teacher_id = User.query.filter_by(username=new_teacher_username).first().id
            current_teacher_id = student_profile.teacher_id
            if int(new_teacher_id) == current_teacher_id:
                flash('新主管老师和现任主管老师不可以是同一人')
                return redirect(url_for('administrator.change_teacher',username=username))
            # 得到过去老师的集合
            past_teacher_str = first_order.past_teachers
            # 如果没有过去的老师，直接把当前老师加入到过去的老师字符串里
            if past_teacher_str is None:
                first_order.past_teachers = str(current_teacher_id)
                db.session.add(first_order)
            # 如果有过去的老师
            else:
                past_teacher_set = set(past_teacher_str.split(';'))
                # 如果当前的主管老师不在过去的老师里，就把当前主管老师加入到过去教师名单里
                if str(current_teacher_id) not in past_teacher_set:
                    first_order.past_teachers = first_order.past_teachers+';'+str(current_teacher_id)
                    db.session.add(first_order)
            # 修改学生的主管老师
            student_profile.teacher_id = int(new_teacher_id)
            # 把新的学生简历提交到数据库
            db.session.add(student_profile)
            # 重定向
            return redirect(url_for('administrator.pre_change_teacher'))
        form.username.data = username
        form.current_teacher.data = User.query.get(student.student_profile.first().teacher_id).name
        # 学生的第一个订单里保存了过去的老师
        old_teacher_ids = first_order.past_teachers
        if old_teacher_ids:
            old_teacher_ids_list = old_teacher_ids.split(';')
            past_teachers_names = User.query.get(old_teacher_ids_list[0]).name
            for oid in old_teacher_ids_list[1:]:
                past_teachers_names=past_teachers_names+';'+User.query.get(oid).name
            form.old_teachers.data = past_teachers_names
        return render_template('administrator/change_teacher.html',form=form)      

# 选课前的准备
@administrator.route('/pre_book_lesson',methods=['GET','POST'])
@login_required
@permission_required(Permission.BOOK_LESSON_FOR_OTHERS)
def pre_book_lesson():
    form = PreBookLessonForm()
    if form.validate_on_submit():
        student_username = form.student.data
        teacher_username = form.teacher.data

app/templates/administrator/assign_teacher.html
{%extends 'administrator/homepage.html'%}
{%import 'bootstrap/wtf.html' as wtf%}
{%block head%}
{{super()}}
{%endblock head%}

{%block title%}Assign Teacher{%endblock title%}

{%block main%}
<div class='col-sm-8 col-md-8' id='main'>
    <div class='panel panel-default'>
        <div class='panel-head'>
            <h3 class='text-center'>新生分配老师</h3>
        </div>
        <div class='panel-body'>
            {{wtf.quick_form(form)}}
        </div>
    </div>
</div>
{%endblock main%}

app/templates/administrator/change_teacher.html
{%extends 'administrator/homepage.html'%}
{% import 'bootstrap/wtf.html' as wtf%}
{%block head%}
{{super()}}
{%endblock head%}

{%block title%}Change Teacher{%endblock title%}

{%block main%}
<div class='col-sm-8 col-md-8' id='main'>
    <div class='panel panel-default'>
        <div class='panel-head'>
            <h3 class='text-center'>更换老师</h3>
        </div>
        <div class='panel-body'>
            {{wtf.quick_form(form)}}
        </div>
    </div>

</div>
{%endblock main%}

app/templates/administrator/check_students.html
{%extends 'administrator/homepage.html'%}
{%block head%}
{{super()}}
{%endblock head%}

{%block title%}Check Students}{%endblock title%}
{%block main%}
<div class='col-sm-8 col-md-8' id='main'>
    <div class='panel panel-default'>
        <div class='panel-head'>
            <h3 class='text-center'>查看学生信息</h3>
        </div>
        <div class='panel-body'>
        
            <table class='table '>
                {%for row in all_students%}
                    <tr>
                        {%for student in row%}
                            <td><a href="{{url_for('administrator.show_student_profile',username=student.username,tab='lessons')}}" class='username'>{{student.username}}</a></td>
                        {%endfor%}
                    </tr>
                    
                {%endfor%}
            </table>
        </div>

    </div>
</div>
{%endblock main%}

app/templates/administrator/homepage.html
{%extends 'base.html'%}
{%block head%}
{{super()}}
<style>
    #main{
        margin-bottom: 300px;
    }
    a:hover{
        cursor: pointer;
    }
    </style>
{%endblock head%}

{%block title%}Personal Center{%endblock title%}

{%block page_content%}
<div class='page-header'>
    <h1>Personal Center</h1>
</div>

<div class='col-sm-3 col-md-3' >
    <ul class='nav nav-pills nav-stacked'>
        <li role="presentation" {%if request.path[:11] == '/personal_c' or request.path[:16]=='/administrator/a'%}class='active'{%endif%}><a href="{{url_for('main.personal_center')}}">New Students</a></li>
        <li role='presentation' {%if request.path[:18]=='/administrator/che' or request.path[:18]=='/administrator/sho'%}class='active'{%endif%}><a href="{{url_for('administrator.check_students')}}">Check Students</a></li>
        <li role="presentation" {%if request.path[:20] == '/administrator/pre_c' or request.path[:18] == '/administrator/cha'%}class='active'{%endif%}><a href="{{url_for('administrator.pre_change_teacher')}}">Change Teacher</a></li>
        <li role='presentation' {%if request.path[:20] == '/administrator/pre_b' or request.path[:16] == '/administrator/b'%}class='active'{%endif%}><a href="{{url_for('administrator.pre_book_lesson')}}">Book Lessons</a></li>
        <li role='presentation' {%if request.path[:27] == '/administrator/pre_modify_s' or request.path[:23] == '/administrator/modify_s'%}class='active'{%endif%}><a href="{{url_for('administrator.pre_modify_schedule')}}">Modify Schedule</a></li>
        <li role='presentation' {%if request.path[:27] == '/administrator/pre_modify_i' or request.path[:24] == '/administrator/modify_pe'%}class='active'{%endif%}><a href="{{url_for('administrator.pre_modify_info')}}">Modify Personal Info</a></li>
        <li role='presentation' {%if request.path[:24] == '/administrator/modify_pa'%} class='active' {%endif%}><a href = "{{url_for('administrator.modify_password')}}">Modify Password</a></li>
        <li role="presentation" {%if request.path[:18] == '/administrator/per'%} class='active' {%endif%}><a href="{{url_for('administrator.personal_info')}}">Personal Information</a></li>    
    </ul>
</div>

{%block main%}
<div class='col-sm-8 col-md-8' id='main'>
    <div class='panel panel-default'>
        {%if students%}
        <div class='panel-head'>
            <h3 class='text-center'>新生名单</h3>
        </div>
        
        <table class='table'>
            <tr>
                <th>学生</th>
                <th>入学时间</th>
                <th>老师</th>
            </tr>
            {%for student in students%}
            <tr>
                <td><a href="#">{{student.username}}</a></td>
                <td>{{"%s-%s-%s %s:00"|format(student.enrollment_time.year,student.enrollment_time.month,student.enrollment_time.day,student.enrollment_time.hour)}}</td>
                <td>{%if student.teacher%}<a>{{student.teacher.name}}</a>{%else%}<a href="{{url_for('administrator.assign_teacher',username=student.username)}}" class='btn btn-primary'>分配老师</a>{%endif%}</td>
            </tr>
            {%endfor%}
        </table>
        {%else%}
        <div class='panel-body'>
            <h3>过去24小时内没有新生入学。</h3>
        </div>
        {%endif%}
    </div>

</div>
{%endblock main%}
{%endblock page_content%}

app/templates/administrator/modify_password.html
{%extends 'administrator/homepage.html'%}
{% import 'bootstrap/wtf.html' as wtf%}
{%block head%}
{{super()}}
{%endblock head%}

{%block title%}Change Teacher{%endblock title%}

{%block main%}
<div class='col-sm-8 col-md-8' id='main'>
    <div class='panel panel-default'>
        <div class='panel-head'>
            <h3 class='text-center'>修改离职教师密码</h3>
        </div>
        <div class='panel-body'>
            {{wtf.quick_form(form)}}
        </div>
    </div>

</div>
{%endblock main%}

app/templates/administrator/personal_info.html
{%extends 'administrator/homepage.html'%}
{%import 'bootstrap/wtf.html' as wtf%}
{%block head%}
{{super()}}
{%endblock head%}

{%block mytitle%}Personal Infomation{%endblock mytitle%}

{%block main%}
<div class='col-sm-8 col-md-8' id='main'>
    <div class='panel panel-default'>
        <div class='panel-body'>
            {{wtf.quick_form(form)}}
        </div>
    </div>
</div>
{%endblock main%}

app/templates/administrator/pre_book_lesson.html
{% extends 'administrator/homepage.html'%}
{% import 'bootstrap/wtf.html' as wtf%}
{%block head%}
{{super()}}
{%endblock head%}

{%block title%}Book Lesson{%endblock title%}
{%block main%}
<div class='col-sm-8 col-md-8' id='main'>
    <div class='panel panel-default'>
        <div class='panel-head'>
            <h3 class='text-center'>请选择要选课的学生和老师</h3>
        </div>
        <div class='panel-body'>
            {{wtf.quick_form(form)}}
        </div>
    </div>
</div>
{%endblock main%}

app/templates/administrator/student_profile.html
{%extends 'administrator/homepage.html'%}

{%block head%}
{{super()}}
<style>
footer{
    margin-top: 200px;
}

ul.nav-tabs{
    margin-bottom: 20px;
}

#user-image{
    width:200px;
    height:200px;

}

.cancel:hover{
    color:blue;
    cursor: pointer;
}
</style>
{%endblock head%}

{%block title%}Student Profile{%endblock title%}

{%block main%}
<div class='col-sm-8 col-md-8' id='main'>
    <ul class="nav nav-tabs">
        <li role="presentation" {%if tab == 'lessons'%}class="active"{%endif%}><a href="{{url_for('administrator.show_student_profile',username=username,tab='lessons')}}">Lessons</a></li>
        <li role="presentation"{%if tab == 'profile'%}class='active'{%endif%}><a href="{{url_for('administrator.show_student_profile',username=username,tab='profile')}}">Profile</a></li>
    </ul>
    {%if tab =='lessons'%}
    <div class = 'panel panel-default'>
        <table class='table'>
            <tr>
                <th>Student</th>
                <th>Teacher</th>
                <th>Time</th>
                <th>Status</th>
                <th>Teacher's comment</th>
                <th>Student's comment</th>
                <th>Student's rate</th>
                <th>Details</th>
            </tr>
            {%for lesson in lessons%}
            <tr>
                <td>{{student.username}}</td>
                <td>{{lesson.teacher.name}}</td>
                <td>{{"%s-%s-%s %s:00"|format(lesson.localtime.year,lesson.localtime.month,lesson.localtime.day,lesson.localtime.hour)}}</td>
                <td>{%if lesson.status == 'Not started'%}{%if moment().valueOf()>moment(lesson.time).valueOf()%}Record{%else%}Not started{%endif%}{%else%}{{lesson.status}}{%endif%}</td>
                <td>{%if lesson.status == 'Not started' and lesson.cancel %}<span class='cancel' lid={{lesson.id}}>[Cancel]</span>{%endif%}{%if lesson.t_comment %}{{lesson.t_comment}}{%endif%}</td>
                <td>{% if moment().valueOf()>moment(lesson.time).valueOf()%} {% if not lesson.s_comment %}Waiting for comment{%else%}{{lesson.s_comment}}{%endif%}{%endif%}</td>
                <td>{% if moment().valueOf()>moment(lesson.time).valueOf()%} {% if not lesson.s_comment %}Waiting for rate{%else%}{{lesson.mark}}{%endif%}{%endif%}</td>
                <td>{%if lesson.status == 'Complete' or lesson.status == 'Tea Late'%}<a href="{{url_for('administrator.check_detail',lesson_id=lesson.id)}}">[Check]</a>{%endif%} {%if current_user.id == lesson.teacher.id%}<a href="{{url_for("teacher.record_lesson",id=lesson.id)}}">[Modify]</a>{%endif%}</td>
            </tr>
            {%endfor%}
        </table>
    </div>
    {%elif tab=='profile'%}
    <div class='panel panel-default'>
        <div class='panel-heading text-center'>
            <strong>基本信息</strong> 
        </div>
        <div class='panel-body'>
            <div class='col-sm-6 col-md-5 col-lg-4'>
            <img {%if student.image %}src="{{url_for('static',filename='media/'+student.image)}}" {%else%}src="{{url_for('static',filename='img/noimage.jpg')}}" {%endif%}class='img-thumbnail' id='user-image'>
            </div><!-- end of image -->
            <div class='col-sm-5 col-md-6 col-lg-7'>
                <table class='table'>
                    <tr>
                        <td><strong>用户名</strong></td>
                        <td>{{student.username}}</td>
                    </tr>
                    <tr>
                        <td><strong>姓名</strong></td>
                        <td>{{student.name}}</td>
                    </tr>
                    <tr>
                        <td><strong>邮箱</strong></td>
                        <td>{{student.email}}</td>
                    </tr>
                    <tr>
                        <td><strong>地址</strong></td>
                        <td>{{student.location}}</td>
                    </tr>
                    <tr>
                        <td><strong>时区</strong></td>
                        <td>{{student.timezone_str}}</td>
                    </tr>
                    <tr>
                        <td><strong>课程类型</strong></td>
                        <td>Regular</td>
                    </tr>
                    <tr>
                        <td><strong>注册时间</strong></td>
                        <td>{{"%s-%s-%s"|format(student.localsince.year,student.localsince.month,student.localsince.day)}}</td>
                    </tr>
                    <tr>
                        <td><strong>最后一次上课</strong></td>
                        <td>2 weeks ago</td>
                    </tr>
                </table>
            </div>
        </div><!-- end of panel body -->
    </div><!-- end of panel -->

    <div class='panel panel-default'>
        <div class='panel-heading text-center'>
            <strong>主管老师的补充信息</strong>
        </div>
        <div class='panel-body'>
            <table class='table'>
                <tr>
                    <td><strong>称呼</strong></td>
                    <td>{{student.student_profile.first().nickname}}</td>
                    <td><strong>性别</strong></td>
                    <td>{{student.student_profile.first().gender}}</td>
                </tr>
                <tr>
                    <td><strong>年龄</strong></td>
                    <td>{{student.student_profile.first().age}}</td>
                    <td><strong>工作情况</strong></td>
                    <td>{{student.student_profile.first().job}}</td>
                </tr>
                <tr>
                    <td><strong>家庭情况</strong></td>
                    <td>{{student.student_profile.first().family}}</td>
                    <td><strong>性格特点</strong></td>
                    <td>{{student.student_profile.first().personality}}</td>
                </tr>
                <tr>
                    <td><strong>兴趣爱好</strong></td>
                    <td>{{student.student_profile.first().hobby}}</td>
                    <td><strong>禁忌话题</strong></td>
                    <td>{{student.student_profile.first().taboo}}</td>
                </tr>
                <tr>
                    <td><strong>学习原因</strong></td>
                    <td>{{student.student_profile.first().reason}}</td>
                    <td><strong>学习目标</strong></td>
                    <td>{{student.student_profile.first().goal}}</td>
                </tr>
                <tr>
                    <td><strong>当前水平</strong></td>
                    <td>{{student.student_profile.first().level}}</td>
                    <td><strong>学习能力</strong></td>
                    <td>{{student.student_profile.first().ability}}</td>
                </tr>
                <tr>
                    <td><strong>是否需要笔记或录音</strong></td>
                    <td>{{student.student_profile.first().notes}}</td>
                    <td><strong>是否需要作业</strong></td>
                    <td>{{student.student_profile.first().homework}}</td>
                </tr>
                <tr>
                    <td><strong>主管老师</strong></td>
                    <td>{{student.teacher.name}}</td>
                    <td><strong>主管老师电话</strong></td>
                    <td>{{student.student_profile.first().teacher_phone}}</td>
                </tr>

            </table>
        </div>

    </div>

    {%endif%}
</div>

{%endblock main%}


{%block scripts%}
{{super()}}
<script>
$(function(){
    //获取csrftoken
    var csrftoken = '{{csrf_token()}}'
    var cancel=$(".cancel");
    cancel.bind("click",function(){
        var id=$(this).attr("lid");
        var answer=confirm('确定要删除这节课吗？请预先和学生达成一致意见。');
        if(answer==true){
            $.ajax({
            url:"{{url_for('administrator.cancel')}}",
            type:"POST",
            data:{id:id},
            headers:{'X-CSRFToken':csrftoken},
            success:function(callback){
                if(callback.status=='ok'){
                    alert("That lesson has been canceled successfully.")
                    window.location.reload();
                }else{
                    alert("Operation failed.");
                }
                }
            })
        }
        
    })
})
</script>
{{moment.include_moment()}}
{%endblock scripts%}